ALTER TABLE `ARTICLES` ENGINE = InnoDB;
CREATE INDEX category_for_article ON ARTICLES (CATEGORY);
ALTER TABLE `ARTICLES` 
ADD CONSTRAINT category_of_article FOREIGN KEY ( `CATEGORY` ) 
REFERENCES `CATEGORIES` (`ID` );

ALTER TABLE `CONTENTS` ENGINE = InnoDB;
CREATE INDEX article ON CONTENTS (ARTICLE);
ALTER TABLE `CONTENTS` 
ADD CONSTRAINT article FOREIGN KEY ( `ARTICLE` ) 
REFERENCES `ARTICLES` (`ID` );

ALTER TABLE `CATEGORIES` ENGINE = InnoDB;
CREATE INDEX parent_category ON CATEGORIES (PARENT);
ALTER TABLE `CATEGORIES`
ADD CONSTRAINT parent_category FOREIGN KEY ( `PARENT` )
REFERENCES `CATEGORIES` (`ID` );

ALTER TABLE `DESCRIPTIONS` ENGINE = InnoDB;
CREATE INDEX image ON DESCRIPTIONS (image);
ALTER TABLE `DESCRIPTIONS` 
ADD CONSTRAINT image FOREIGN KEY ( `IMAGE` ) 
REFERENCES `IMAGES` (`ID` );

ALTER TABLE `IMAGES` ENGINE = InnoDB;
CREATE INDEX category_for_image ON IMAGES (CATEGORY);
ALTER TABLE `IMAGES` 
ADD CONSTRAINT category_of_image FOREIGN KEY ( `CATEGORY` ) 
REFERENCES `CATEGORIES` (`ID` );

ALTER TABLE `CONFIGURED_TAGS` ENGINE = InnoDB;
CREATE INDEX category_tag ON CONFIGURED_TAGS (CATEGORY_ID);
ALTER TABLE `CONFIGURED_TAGS` 
ADD CONSTRAINT tags_of_category FOREIGN KEY ( `CATEGORY_ID` ) 
REFERENCES `CATEGORIES` (`ID` );
