CREATE TABLE USERS
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 USER VARCHAR(50),
 PASSWORD CHAR(32),
 ROLE VARCHAR(50));
CREATE TABLE CATEGORIES
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CATEGORY VARCHAR(120)
);
CREATE TABLE TAGS
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 TAG VARCHAR(120),
 ITEM_ID INTEGER,
 ITEM_TYPE VARCHAR(20)
);
CREATE TABLE CONFIGURED_TAGS
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 TAG VARCHAR(120),
 CATEGORY_ID INTEGER,
 ITEM_TYPE VARCHAR(20),
 DEFAULT_TAG TINYINT(1)
);
CREATE TABLE ARTICLES
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 IMAGE VARCHAR(50),
 CATEGORY INTEGER,
 DISPLAY_ORDER INTEGER,
 PUBLISH_DATE TIMESTAMP,
 PUBLISHED TINYINT(1)
);
CREATE TABLE CONTENTS
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 ARTICLE INTEGER,
 TITLE VARCHAR(120),
 SLUG VARCHAR(120),
 TEXT LONGTEXT,
 LANGUAGE VARCHAR(2));
CREATE TABLE IMAGES
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 IMAGE VARCHAR(50),
 CATEGORY INTEGER
);
CREATE TABLE DESCRIPTIONS
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 IMAGE INTEGER,
 TITLE VARCHAR(50),
 DESCRIPTION TEXT,
 LANGUAGE VARCHAR(2));
ALTER TABLE CATEGORIES
ADD PARENT INTEGER DEFAULT NULL;
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 USER VARCHAR(50),
 PASSWORD_HASH CHAR(31),
 PASSWORD_SALT CHAR(22),
 ROLE VARCHAR(50));
ALTER TABLE ARTICLES
MODIFY PUBLISH_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE ACTIVITY_LOG
(ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 USER VARCHAR(100),
 ACTION VARCHAR(100),
 ENTITY_TYPE VARCHAR(100),
 ENTITY_ID INTEGER,
 TIMESTAMP TIMESTAMP
);
