CREATE TABLE FOO
(ID INTEGER PRIMARY KEY AUTOINCREMENT,
 TEXT VARCHAR(50),
 CATEGORY INTEGER,
 DISPLAY_ORDER INTEGER,
 PUBLISH_DATE DATE,
 PUBLISHED TINYINT(1),
 SLUG VARCHAR(120)
);
CREATE TABLE PUPPET
(ID INTEGER PRIMARY KEY AUTOINCREMENT,
 TEXT VARCHAR(50),
 DISPLAY_ORDER INTEGER,
 PUBLISH_DATE DATE,
 PUBLISHED TINYINT(1),
 SLUG VARCHAR(120)
);
